Repository FRONT-END-BOOTCAMP-PLUS-4/gamechu, pull requests merged in 2025-05, with the labels that each got.

#7 [file/#6]: API 폴더 구조 작성
  app/api/arenas/[id]/chattings/route.ts
  app/api/arenas/[id]/route.ts
  app/api/arenas/[id]/votes/route.ts
  app/api/arenas/route.ts
  app/api/auth/email-check/route.ts
  app/api/auth/login/route.ts
  app/api/auth/signup/route.ts
  app/api/games/[id]/route.ts
  app/api/games/route.ts
  app/api/member/arenas/[id]/chattings/route.ts
  app/api/member/arenas/[id]/route.ts
  app/api/member/arenas/[id]/votes/route.ts
  app/api/member/arenas/route.ts
  app/api/member/change-password/route.ts
  app/api/member/games/[gameId]/reviews/[reviewsId]/route.ts
  app/api/member/games/[gameId]/reviews/route.ts
  app/api/member/notifications/[id]/route.ts
  app/api/member/notifications/route.ts
  app/api/member/profile/route.ts
  app/api/member/review-likes/[gameId]/route.ts
  app/api/member/scores/route.ts
  app/api/member/wishlists/[id]/route.ts
  app/api/member/wishlists/route.ts
  app/api/member/withdraw/route.ts
  app/api/review-likes/[gameId]/route.ts
  app/api/scores/route.ts
Labels: file

#14 [feat/#13]: 데이터 저장을 위한 seed 작성
  prisma/generated/package.json
  prisma/generated/schema.prisma
  prisma/schema.prisma
  prisma/seed.ts
  prisma/test.ts
Labels: feat

#34 [feat/#33] Pager 컴포넌트 및 테스트 페이지 구현
  app/components/Pager.tsx
  app/test/pager/page.tsx
Labels: feat

#40 [feat/#32] 투기장 상세 페이지 UI
  app/(base)/arena/[id]/page.tsx
  app/(base)/arena/components/.gitkeep
  app/(base)/arena/components/AnrenaVote.tsx
  app/(base)/arena/components/ArenaChatting.tsx
  app/(base)/arena/components/ArenaHeader.tsx
  app/(base)/arena/components/ArenaInfo.tsx
  package-lock.json
  package.json
  public/icons/.gitkeep
  public/icons/arena2.svg
  public/icons/arrowDown.svg
  public/icons/chatButton.svg
  public/icons/infoCalendar.svg
  public/icons/infoMessage.svg
  public/icons/infoTime.svg
  public/icons/teamA.svg
  public/icons/teamB.svg
  tailwind.config.ts
Labels: feat

#44 [feat/#42] 알림 usecase 및 dto 작성
  backend/notification-record/application/usecase/CreateNotificationRecordUsecase.ts
  backend/notification-record/application/usecase/DeleteNotificationRecordUsecase.ts
  backend/notification-record/application/usecase/GetNotificationRecordUsecase.ts
  backend/notification-record/application/usecase/dto/.gitkeep
  backend/notification-record/application/usecase/dto/CreateNotificationRecordDto.ts
  backend/notification-record/application/usecase/dto/GetNotificationRecordDto.ts
  backend/notification-record/application/usecase/dto/NotificationRecordDto.ts
  backend/notification-record/application/usecase/dto/NotificationRecordListDto.ts
Labels: feat

#56 feat/#54 토큰에서 멤버 아이디 가져오는 유틸 함수 추가
  app/(auth)/log-in/page.tsx
  app/(base)/profile/page.tsx
  stores/AuthStore.ts
  utils/GetAuthUserId.client.ts
  utils/GetAuthUserId.server.ts
  utils/cookieStorage.ts
Labels: feat

#58 [fix/#57]: 헤더 수정
  app/components/Header.tsx
Labels: fix

#66 [feat/#52] 투기장 상세 백엔드 및 채팅 기능 구현
  app/(base)/arena/[id]/page.tsx
  app/(base)/arena/components/AnrenaVote.tsx
  app/(base)/arena/components/ArenaChatList.tsx
  app/(base)/arena/components/ArenaChatting.tsx
  app/(base)/arena/components/ArenaHeader.tsx
  app/(base)/arena/components/ArenaInfo.tsx
  app/(base)/arena/components/ArenaInputBox.tsx
  app/(base)/arena/components/ArenaRecruiting.tsx
  app/(base)/arena/components/ArenaWaiting.tsx
  app/api/arenas/[id]/chattings/route.ts
  app/api/arenas/[id]/participants/route.ts
  app/api/arenas/[id]/route.ts
  app/components/Button.tsx
  app/globals.css
  backend/arena/application/usecase/GetArenaDetailUsecase.ts
  backend/arena/application/usecase/GetArenaParticipantsUsecase.ts
  backend/arena/application/usecase/UpdateArenaStatusUsecase.ts
  backend/arena/application/usecase/dto/.gitkeep
  backend/arena/application/usecase/dto/ArenaDetailDto.ts
  backend/arena/application/usecase/dto/ArenaParticipantsDto.ts
  backend/arena/domain/repositories/.gitkeep
  backend/arena/domain/repositories/ArenaRepository.ts
  backend/arena/infra/repositories/prisma/.gitkeep
  backend/arena/infra/repositories/prisma/PrismaArenaRepository.ts
  hooks/.gitkeep
  hooks/useArenaSocket.ts
  package-lock.json
  package.json
  server.ts
  socket.ts
  stores/useArenaStore.ts
  tailwind.config.ts
  tsconfig.json
  tsconfig.server.json
  types/arena-status.d.ts
Labels: feat

#67 [feat/#62] 게임 상세페이지 댓글 달기 및 조회 기능 구현
  app/(base)/game/[gameId]/components/Comment.tsx
  app/(base)/game/[gameId]/components/CommentCard.tsx
  app/(base)/game/[gameId]/components/GameInfoCard.tsx
  app/(base)/game/[gameId]/components/GameTitleCard.tsx
  app/(base)/game/[gameId]/components/ReviewSelector.tsx
  app/(base)/game/[gameId]/components/StarRating.tsx
  app/(base)/game/[gameId]/page.tsx
  app/(base)/game/[id]/components/CommentCard.tsx
  app/(base)/game/[id]/page.tsx
  app/api/reviews/[reviewId]/route.ts
  app/api/reviews/game/[gameId]/route.ts
  app/api/reviews/member/[memberId]/route.ts
  app/api/reviews/route.ts
  app/test/game-detail/page.tsx
  app/test/gamecard-test/page.tsx
  backend/member/infra/repositories/prisma/PrismaMemberRepository.ts
  backend/review/application/usecase/CreateReviewUsecase.ts
  backend/review/application/usecase/DeleteReviewUsecase.ts
  backend/review/application/usecase/GetReviewsByGameIdUsecase.ts
  backend/review/application/usecase/GetReviewsByMemberIdUsecase.ts
  backend/review/application/usecase/UpdateReviewUsecase.ts
  backend/review/application/usecase/dto/.gitkeep
  backend/review/application/usecase/dto/CreateReviewDto.ts
  backend/review/application/usecase/dto/ReviewDto.ts
  backend/review/application/usecase/dto/UpdateReviewDto.ts
  backend/review/domain/repositories/.gitkeep
  backend/review/domain/repositories/ReviewRepository.ts
  backend/review/infra/repositories/prisma/.gitkeep
  backend/review/infra/repositories/prisma/PrismaReviewRepository.ts
  next.config.ts
  public/icons/delete.svg
  public/icons/hamburger.svg
  public/search.json
  public/typing.json
  tailwind.config.ts
Labels: feat

#87 [fix/#85] 채팅 관련 버그 수정
  backend/chatting/application/usecase/dto/ChattingDto.ts
  hooks/useArenaChatManagement.ts
Labels: fix

#115 [fix#/111] 로그아웃 시 채팅이 보이지 않는 문제 해결
  app/api/arenas/[id]/chattings/route.ts
  hooks/useArenaChatManagement.ts
Labels: fix

#123 [feat/#116] 투기장 score 로직 구현
  app/api/arenas/[id]/end/route.ts
  app/api/arenas/[id]/route.ts
  backend/arena/application/usecase/EndArenaUsecase.ts
  backend/arena/application/usecase/UpdateArenaStatusUsecase.ts
  backend/score-policy/domain/ScorePolicy.ts
  hooks/useArenaAutoStatus.ts
  hooks/useArenaAutoStatusDetail.ts
Labels: feat

#126 [refactor/#125] 투기장 상세 티어, img태그 next Image로 변경
  app/(base)/arenas/[id]/components/ArenaDetailChatList.tsx
  app/(base)/arenas/[id]/components/ArenaDetailHeader.tsx
  app/(base)/arenas/[id]/components/ArenaDetailInfo.tsx
  app/(base)/arenas/[id]/components/ArenaDetailInputBox.tsx
  app/(base)/arenas/[id]/components/ArenaDetailRecruiting.tsx
  app/(base)/arenas/[id]/components/ArenaDetailVote.tsx
  app/(base)/arenas/[id]/page.tsx
  app/api/arenas/[id]/route.ts
  backend/arena/application/usecase/GetArenaDetailUsecase.ts
  backend/arena/application/usecase/dto/ArenaDetailDto.ts
  backend/arena/infra/repositories/prisma/PrismaArenaRepository.ts
Labels: refactor
