Repository FRONT-END-BOOTCAMP-PLUS-4/gamechu, pull requests merged in 2025-06, with the labels that each got.

#137 [refactor/#129] 투기장 백엔드 리팩토링
  app/(base)/arenas/components/CompleteArenaSection.tsx
  app/(base)/arenas/components/DebatingArenaSection.tsx
  app/(base)/arenas/components/RecruitingArenaSection.tsx
  app/(base)/arenas/components/VotingArenaSection.tsx
  app/(base)/arenas/components/WaitingArenaSection.tsx
  backend/arena/application/usecase/GetArenaDetailUsecase.ts
  backend/arena/application/usecase/GetArenaListUsecase.ts
  backend/arena/domain/repositories/ArenaRepository.ts
  backend/arena/infra/repositories/prisma/PrismaArenaRepository.ts
  hooks/useArenaAutoStatus.ts
Labels: refactor

#147 [refactor/#144] 소켓 서버 분리 작업
  package.json
  server.ts
  socket.ts
  tsconfig.json
  tsconfig.server.json
Labels: refactor

#151 [fix/#142] 빌드 오류 최종 수정 및 기타 오류 수정
  app/(auth)/log-in/LoginPage.tsx
  app/(auth)/log-in/page.tsx
  app/(base)/arenas/ArenaPage.tsx
  app/(base)/arenas/components/CompleteArenaCard.tsx
  app/(base)/arenas/components/CompleteArenaSection.tsx
  app/(base)/arenas/components/DebatingArenaCard.tsx
  app/(base)/arenas/components/DebatingArenaSection.tsx
  app/(base)/arenas/components/RecruitingArenaCard.tsx
  app/(base)/arenas/components/RecruitingArenaSection.tsx
  app/(base)/arenas/components/SelectedArenaSection.tsx
  app/(base)/arenas/components/VoteStatusBar.tsx
  app/(base)/arenas/components/VotingArenaCard.tsx
  app/(base)/arenas/components/VotingArenaSection.tsx
  app/(base)/arenas/components/WaitingArenaCard.tsx
  app/(base)/arenas/components/WaitingArenaSection.tsx
  app/(base)/arenas/page.tsx
  app/(base)/games/[gameId]/components/Comment.tsx
  app/(base)/games/[gameId]/components/CommentCard.tsx
  app/(base)/profile/components/PointHistoryCard.tsx
  app/components/Button.tsx
  app/components/Footer.tsx
  app/components/Input.tsx
  app/components/LandingCard.tsx
Labels: fix, refactor

#150 [build/#149]: GitHub Actions 등록
  .github/workflows/deploy-on-ubuntu-server.yml
Labels: build

#155 [Style/#132]: 404 에러 페이지 커스터마이징
  app/components/ClientNotFoundView.tsx
  app/components/NotFoundLottie.tsx
  app/not-found.tsx
  public/404.json
Labels: style

#161 [chore/#160] workflow 재수정
  .github/workflows/deploy-on-ubuntu-server.yml
Labels: chore

#156 [chore/#154] 환경변수 설정 및 사용하지 않는 파일 삭제
  hooks/useArenaStartTimer.ts
  hooks/useCloseArenaTimer.ts
  hooks/useVoteStartTimer.ts
  socket.ts
Labels: chore

#167 [chore/#166] GitHub Actions 구조 변경
  .github/workflows/deploy-on-ubuntu-server.yml
Labels: chore

#172 [fix/#171] 투기장 상태변경 KTC -> UTC 기준으로 수정
  hooks/useArenaAutoStatus.ts
  hooks/useArenaAutoStatusDetail.ts
Labels: fix

#174 [fix/#173] 투기장 상태변경 UTC -> KST 기준으로 재수정
  app/(base)/arenas/[id]/components/ArenaDetailInfo.tsx
  app/(base)/arenas/[id]/page.tsx
  backend/arena/application/usecase/GetArenaDetailUsecase.ts
  backend/arena/application/usecase/dto/ArenaDetailDto.ts
  hooks/useArenaAutoStatus.ts
Labels: fix

#179 [chore/#178] socket.ts 경로 수정
  socket.ts
Labels: chore
